### PR TITLE
chore: Remove obsolete utils

### PR DESCRIPTION
**Pull request by pan-kot**
Removing the no longer used utils.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by just-boris** [comment]
Why is this not a direct revert of https://github.com/cloudscape-design/collection-hooks/commit/b37682ee59b49158403fdde7815a25e4698f3909

**Comment by pan-kot** [comment]
> b37682e

Thanks, I just didn't think of it.

**Comment by rubencarvalho** [comment]
Did we have a dry-run of these changes?

**Review by rubencarvalho — APPROVED** [review]

**Comment by pan-kot** [comment]
> Did we have a dry-run of these changes?

Yes

**Pull request merged**
